//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrder.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Orders
    {
        [Key]
        public int Id { get; set; }
        public int Qty { get; set; }
        public int Unit_Price { get; set; }
        public float Order_Bill { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> FkProdId { get; set; }
        public string FkInvoiceID { get; set; }

        [ForeignKey("FkInvoiceID")]
        public virtual InvoiceModels InvoiceModels { get; set; }
        [ForeignKey("FkProdId")]
        public virtual Products Products { get; set; }
    }
}
